#!/usr/bin/env python3
"""Sparse exact/modular prototype for compound Hessian minors.

First target:
  det_4 versus F = z * per_3 in 16 ambient variables.

Constructs the symmetric second compound C_2(Hess(f)), computes
vector-valued catalecticant ranks, and graded ranks of the ideal generated by
its entries.  Polynomial arithmetic is exact over Z; ranks are computed over
several finite fields.  Full-domain ranks are thereby exact over Q whenever
an a priori domain upper bound is met.
"""
from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import math
import time
from collections import Counter
from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Sequence, Tuple

Mon = Tuple[int, ...]  # sorted multiset of variable indices
Poly = Dict[Mon, int]

N = 16
DEG_F = 4
R = 2
Q = R * (DEG_F - 2)  # degree of compound-minor entries = 4
PRIMES = (1009, 10007, 32003)


def perm_sign(p: Sequence[int]) -> int:
    inv = sum(p[i] > p[j] for i in range(len(p)) for j in range(i + 1, len(p)))
    return -1 if inv & 1 else 1


def det4_terms() -> Poly:
    out: Poly = {}
    for p in itertools.permutations(range(4)):
        mon = tuple(sorted(4 * i + p[i] for i in range(4)))
        out[mon] = perm_sign(p)
    return out


def padded_per3_terms() -> Poly:
    # variable 0 is z; variables 1..9 are the 3x3 permanent variables;
    # 10..15 are unused ambient directions.
    out: Poly = {}
    for p in itertools.permutations(range(3)):
        mon = tuple(sorted((0,) + tuple(1 + 3 * i + p[i] for i in range(3))))
        out[mon] = 1
    return out


def poly_add(a: Poly, b: Poly, scale_b: int = 1) -> Poly:
    out = dict(a)
    for m, c in b.items():
        z = out.get(m, 0) + scale_b * c
        if z:
            out[m] = z
        elif m in out:
            del out[m]
    return out


def poly_mul(a: Poly, b: Poly) -> Poly:
    if not a or not b:
        return {}
    out: Poly = {}
    for ma, ca in a.items():
        for mb, cb in b.items():
            m = tuple(sorted(ma + mb))
            out[m] = out.get(m, 0) + ca * cb
    return {m: c for m, c in out.items() if c}


def derivative(poly: Poly, alpha: Mon) -> Poly:
    if not alpha:
        return dict(poly)
    ac = Counter(alpha)
    out: Poly = {}
    for m, c in poly.items():
        mc = Counter(m)
        if any(mc[i] < q for i, q in ac.items()):
            continue
        factor = 1
        for i, q in ac.items():
            v = mc[i]
            for j in range(q):
                factor *= v - j
        rem = list(m)
        for i in alpha:
            rem.remove(i)
        mt = tuple(rem)
        out[mt] = out.get(mt, 0) + c * factor
    return {m: c for m, c in out.items() if c}


def hessian(poly: Poly) -> List[List[Poly]]:
    H: List[List[Poly]] = [[{} for _ in range(N)] for _ in range(N)]
    for i in range(N):
        for j in range(i, N):
            p = derivative(poly, tuple(sorted((i, j))))
            H[i][j] = p
            H[j][i] = p
    return H


def pairs(n: int) -> List[Tuple[int, int]]:
    return list(itertools.combinations(range(n), 2))


def compound2_symmetric(H: List[List[Poly]]) -> Tuple[List[Tuple[Tuple[int, int], Tuple[int, int]]], List[Poly]]:
    ps = pairs(N)
    labels = []
    comps: List[Poly] = []
    for a, I in enumerate(ps):
        i, j = I
        for b in range(a, len(ps)):
            K = ps[b]
            k, l = K
            # det H[I,K] = H[i,k]H[j,l] - H[i,l]H[j,k]
            p = poly_add(poly_mul(H[i][k], H[j][l]), poly_mul(H[i][l], H[j][k]), -1)
            labels.append((I, K))
            comps.append(p)
    return labels, comps


def multiset_monomials(n: int, degree: int) -> Iterator[Mon]:
    yield from itertools.combinations_with_replacement(range(n), degree)


def active_variables(poly: Poly) -> List[int]:
    return sorted({i for m in poly for i in m})


def sparse_rank_rows(rows: Iterable[Dict[object, int]], p: int) -> Tuple[int, List[object]]:
    """Incremental sparse row rank over F_p, pivoting by minimum hashable key.

    Keys must have a deterministic total order.
    """
    piv: Dict[object, Dict[object, int]] = {}
    order: List[object] = []
    for raw in rows:
        row = {j: v % p for j, v in raw.items() if v % p}
        while row:
            lead = min(row)
            base = piv.get(lead)
            if base is None:
                inv = pow(row[lead], -1, p)
                row = {j: (v * inv) % p for j, v in row.items() if (v * inv) % p}
                piv[lead] = row
                order.append(lead)
                break
            f = row[lead]
            if f:
                for j, v in base.items():
                    z = (row.get(j, 0) - f * v) % p
                    if z:
                        row[j] = z
                    elif j in row:
                        del row[j]
    return len(piv), order


def catalecticant_rows(components: Sequence[Poly], k: int, active_only: Sequence[int] | None = None):
    vars_ = range(N) if active_only is None else active_only
    for alpha in itertools.combinations_with_replacement(vars_, k):
        row: Dict[Tuple[int, Mon], int] = {}
        for cidx, comp in enumerate(components):
            for beta, coeff in derivative(comp, alpha).items():
                row[(cidx, beta)] = coeff
        yield alpha, row


def component_hash(labels, components) -> str:
    payload = []
    for lab, p in zip(labels, components):
        payload.append([lab, [[list(m), c] for m, c in sorted(p.items())]])
    raw = json.dumps(payload, separators=(",", ":"), sort_keys=False).encode()
    return hashlib.sha256(raw).hexdigest()


def normalized_poly_key(poly: Poly) -> Tuple[Tuple[Mon, int], ...] | None:
    if not poly:
        return None
    items = sorted(poly.items())
    coeffs = [abs(c) for _, c in items]
    g = 0
    for c in coeffs:
        g = math.gcd(g, c)
    items = [(m, c // g) for m, c in items]
    if items[0][1] < 0:
        items = [(m, -c) for m, c in items]
    return tuple(items)


def unique_nonzero_components(components: Sequence[Poly]) -> List[Poly]:
    seen = set()
    out = []
    for p in components:
        key = normalized_poly_key(p)
        if key is None or key in seen:
            continue
        seen.add(key)
        out.append(p)
    return out


def fitting_rows(generators: Sequence[Poly], s: int):
    shifts = list(multiset_monomials(N, s))
    for gi, g in enumerate(generators):
        for shift in shifts:
            row: Dict[Mon, int] = {}
            for m, c in g.items():
                outm = tuple(sorted(m + shift))
                row[outm] = row.get(outm, 0) + c
            yield (gi, shift), row


def run_form(name: str, f: Poly, max_fitting_s: int, max_cat_k: int, primes: Sequence[int]) -> dict:
    t0 = time.time()
    H = hessian(f)
    labels, comps = compound2_symmetric(H)
    active = active_variables(f)
    nonzero = sum(bool(p) for p in comps)
    uniq = unique_nonzero_components(comps)
    rec = {
        "form": name,
        "ambient_variables": N,
        "active_variables": active,
        "active_variable_count": len(active),
        "input_monomials": len(f),
        "compound_r": R,
        "compound_entry_degree": Q,
        "compound_coordinates_symmetric": len(comps),
        "compound_nonzero_coordinates": nonzero,
        "compound_unique_nonzero_polynomials_up_to_scalar": len(uniq),
        "compound_sha256": component_hash(labels, comps),
        "catalecticants": [],
        "fitting_graded_pieces": [],
    }

    # Vector-valued catalecticants.  We include all ambient derivative rows;
    # zero rows in unused directions are retained conceptually.
    for k in range(max_cat_k + 1):
        alphas_rows = list(catalecticant_rows(comps, k))
        ranks = {}
        pivots = {}
        for p in primes:
            rank, pv = sparse_rank_rows((row for _, row in alphas_rows), p)
            ranks[str(p)] = rank
            pivots[str(p)] = len(pv)
        ambient_domain = math.comb(N + k - 1, k)
        active_upper = math.comb(len(active) + k - 1, k)
        exact = len(set(ranks.values())) == 1 and next(iter(ranks.values())) == active_upper
        rec["catalecticants"].append({
            "order": k,
            "ambient_domain_dimension": ambient_domain,
            "active_domain_upper_bound": active_upper,
            "ranks_mod_p": ranks,
            "rank_over_Q_exact": next(iter(ranks.values())) if exact else None,
            "exactness_reason": "modular rank reaches the a priori active-variable domain upper bound" if exact else None,
            "nonzero_rows": sum(bool(row) for _, row in alphas_rows),
        })

    # Graded pieces of the ideal generated by scalar compound entries.
    # Duplicate/scalar-multiple generators are removed without changing the ideal.
    for s in range(max_fitting_s + 1):
        rows_factory = lambda: (row for _, row in fitting_rows(uniq, s))
        ranks = {}
        for p in primes:
            rank, _ = sparse_rank_rows(rows_factory(), p)
            ranks[str(p)] = rank
        degree = Q + s
        ambient_dim = math.comb(N + degree - 1, degree)
        # Since generators use only active variables but shifts can use all variables,
        # the ambient polynomial-space dimension is the only unconditional upper bound.
        exact = len(set(ranks.values())) == 1 and next(iter(ranks.values())) == ambient_dim
        rec["fitting_graded_pieces"].append({
            "shift_degree_s": s,
            "graded_degree": degree,
            "number_of_reduced_generators": len(uniq),
            "number_of_generated_rows": len(uniq) * math.comb(N + s - 1, s),
            "ambient_polynomial_dimension": ambient_dim,
            "ranks_mod_p": ranks,
            "rank_over_Q_exact": next(iter(ranks.values())) if exact else None,
            "exactness_reason": "modular rank reaches the full ambient graded-piece dimension" if exact else None,
        })

    rec["elapsed_seconds"] = round(time.time() - t0, 3)
    return rec


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--max-fitting-s", type=int, default=1)
    ap.add_argument("--max-cat-k", type=int, default=2)
    ap.add_argument("--forms", choices=("both","det4","z_per3"), default="both")
    ap.add_argument("--prime-count", type=int, choices=(1,2,3), default=3)
    args = ap.parse_args()

    forms = [("det4", det4_terms()), ("z_per3", padded_per3_terms())]
    if args.forms != "both":
        forms = [x for x in forms if x[0] == args.forms]
    primes = PRIMES[:args.prime_count]
    result = {
        "schema": "reverse_hessian.compound_hessian_r2.v1",
        "status": "EXPLORATORY-COMP; exact polynomial construction, modular ranks unless explicitly certified exact",
        "variable_convention": {
            "det4": "variables 0..15 are the 4x4 matrix entries in row-major order",
            "z_per3": "variable 0 is z, variables 1..9 are per_3 entries, variables 10..15 are unused",
        },
        "primes": list(primes),
        "forms": [],
    }
    for name, f in forms:
        print(f"[{name}] building and ranking...", flush=True)
        rec = run_form(name, f, args.max_fitting_s, args.max_cat_k, primes)
        result["forms"].append(rec)
        print(json.dumps({
            "form": name,
            "nonzero_compound": rec["compound_nonzero_coordinates"],
            "unique_generators": rec["compound_unique_nonzero_polynomials_up_to_scalar"],
            "cat": [x["ranks_mod_p"][str(primes[0])] for x in rec["catalecticants"]],
            "fitting": [x["ranks_mod_p"][str(primes[0])] for x in rec["fitting_graded_pieces"]],
            "seconds": rec["elapsed_seconds"],
        }), flush=True)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
